# Generated by Django 4.2.1 on 2023-05-19 02:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_statshour_cv_alter_statshour_fq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statshour',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
