name: More CI

on: [push]

jobs:
  Build-Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Reqs
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Testing Django
      run: |
        python3 manage.py test

  Deploy-PreProd:
    runs-on: ubuntu-latest
    environment:
      name: pre-production
    needs: Build-Test

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Sending Server
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
        EXCLUDE: "/dist/, /node_modules/"
        SCRIPT_BEFORE: |
          whoami
          ls -al
        SCRIPT_AFTER: |
          whoami
          ls -al
          echo $RSYNC_STDOUT

  Deploy-Productions:
    runs-on: ubuntu-latest
    environment:
      name: production
    needs: Deploy-PreProd

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Sending Server
      run: echo A
