name: Learning2

on: [push]

jobs:
    Job1:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v1
        - run: echo Job 1 Executado!!!!!!!!!!
        environment:
            name: job1
    job2:
        runs-on: ubuntu-latest
        environment:
            name: job2
        needs: Job1

        steps:
        - uses: actions/checkout@v1
        - run: echo Job 1 Executado!!!!!!!!!!
