name: More CI

on: [push]

jobs:
  Build-Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Reqs
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Testing Django
      run: python3 manage.py test

  Deploy-Dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
    needs: Build-Test

    steps:
    - name: Checkout
    - uses: actions/checkout@v1
    - name: Sending Server
    - run: echo Deploy Dev!!!!!!!!!

  Deploy-Productions:
    runs-on: ubuntu-latest
    environment:
      name: production
    needs: Deploy-Production

    steps:
    - name: Checkout
    - uses: actions/checkout@v1
    - name: Sending Server
    - run: echo Productio  Deploy !!!!!!
