name: More CI

on: [push]

jobs:
  Build-Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Reqs
      run: echo Job Test Executado

  Deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    needs: Build-Test

    steps:
    - uses: actions/checkout@v1
    - run: echo Job 1 Executado!!!!!!!!!!
